name: flutter_moneymanager
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  flutter_slidable: ^3.1.0
  flutter_speed_dial: ^7.0.0
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  fl_chart: ^0.68.0
  http: ^1.2.1
  firebase_database: ^11.0.1
  cloud_firestore: ^5.0.1
  provider: ^6.1.2
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.1.0
  flutter_svg: ^2.0.10+1
  printing: ^5.12.0
  pdf: ^3.10.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
