// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaxtCRauXpc5CCiyToc1Ue37gozbycBX8',
    appId: '1:851237464450:web:039557c47bb3050a43c79b',
    messagingSenderId: '851237464450',
    projectId: 'ambw-auth-171bb',
    authDomain: 'ambw-auth-171bb.firebaseapp.com',
    storageBucket: 'ambw-auth-171bb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcbNufpvZE8vT2EfZyonieMZqOUDy7eGc',
    appId: '1:851237464450:android:c0b6d95e525758c243c79b',
    messagingSenderId: '851237464450',
    projectId: 'ambw-auth-171bb',
    storageBucket: 'ambw-auth-171bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGJFcbE_27jCBxjzSbrkyRNGv-C3B7Vms',
    appId: '1:851237464450:ios:977cb7470b9b2cc343c79b',
    messagingSenderId: '851237464450',
    projectId: 'ambw-auth-171bb',
    storageBucket: 'ambw-auth-171bb.appspot.com',
    iosBundleId: 'com.example.flutterMoneymanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGJFcbE_27jCBxjzSbrkyRNGv-C3B7Vms',
    appId: '1:851237464450:ios:977cb7470b9b2cc343c79b',
    messagingSenderId: '851237464450',
    projectId: 'ambw-auth-171bb',
    storageBucket: 'ambw-auth-171bb.appspot.com',
    iosBundleId: 'com.example.flutterMoneymanager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaxtCRauXpc5CCiyToc1Ue37gozbycBX8',
    appId: '1:851237464450:web:146c6c5b124ee96a43c79b',
    messagingSenderId: '851237464450',
    projectId: 'ambw-auth-171bb',
    authDomain: 'ambw-auth-171bb.firebaseapp.com',
    storageBucket: 'ambw-auth-171bb.appspot.com',
  );
}
